Reach New Heights Section
inovex/scrumlr.io-landing-page pull request #24
Opened 2023-08-13 14:33 UTC by brandstetterm

2023-08-29 13:21 UTC, Resaki1 requested changes

2023-08-29 13:21 UTC, Resaki1 commented on src/components/Link/Link.scss
> +
```suggestion
transition: all 0.2s ease-in-out;

```

2023-08-29 13:21 UTC, Resaki1 commented on src/views/ReachNewHeights/ReachNewHeights.scss
> +    margin: 0 !important;
why is the `!important` needed?

2023-08-29 13:21 UTC, Resaki1 commented on src/views/ReachNewHeights/ReachNewHeights.scss
> +    font-size: 16px;
I've set the font sizes and line-heights for these elements inside of Layout.astro in my open PR, so that all elements are consistent. If you're ok with that change, it can be removed here

2023-08-29 13:37 UTC, brandstetterm commented on src/views/ReachNewHeights/ReachNewHeights.scss
> +    margin: 0 !important;
Removed it

2023-08-29 13:38 UTC, brandstetterm commented on src/views/ReachNewHeights/ReachNewHeights.scss
> +    font-size: 16px;
It seems like it's no always consistent, that's why I would stick with it for now

2023-08-30 09:10 UTC, Resaki1 approved these changes

2023-08-30 09:18 UTC, merged